version: '3.8'

services:

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
      - /app/server/dist

  www:
    build:
      context: .
      dockerfile: apps/www/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://server:4000
    volumes:
      - ./apps/www:/app/apps/www
      - /app/apps/www/node_modules
      - /app/apps/www/.next
    depends_on:
      - server

volumes:
  node_modules:
  dist:
